// default package
// Generated Mar 5, 2023, 4:36:11 PM by Hibernate Tools 6.0.0.Alpha2

package gov.iti.jets.healthifyme.models;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,catalog="healthifyme"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class Order  implements java.io.Serializable {


     private OrderId id;
     private User user;
     private Date date;
     private long totalPrice;
     private String orderStatus;
     private Set<OrderHasProduct> orderHasProducts = new HashSet<OrderHasProduct>(0);

    public Order() {
    }

	
    public Order(OrderId id, User user, Date date, long totalPrice, String orderStatus) {
        this.id = id;
        this.user = user;
        this.date = date;
        this.totalPrice = totalPrice;
        this.orderStatus = orderStatus;
    }
    public Order(OrderId id, User user, Date date, long totalPrice, String orderStatus, Set<OrderHasProduct> orderHasProducts) {
       this.id = id;
       this.user = user;
       this.date = date;
       this.totalPrice = totalPrice;
       this.orderStatus = orderStatus;
       this.orderHasProducts = orderHasProducts;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", unique=true, nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public OrderId getId() {
        return this.id;
    }
    
    public void setId(OrderId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="total_price", nullable=false, precision=10, scale=0)
    public long getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(long totalPrice) {
        this.totalPrice = totalPrice;
    }

    
    @Column(name="order_status", nullable=false, length=45)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderHasProduct> getOrderHasProducts() {
        return this.orderHasProducts;
    }
    
    public void setOrderHasProducts(Set<OrderHasProduct> orderHasProducts) {
        this.orderHasProducts = orderHasProducts;
    }




}


