// default package
// Generated Mar 5, 2023, 4:36:11 PM by Hibernate Tools 6.0.0.Alpha2
package gov.iti.jets.healthifyme.models;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinColumns;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * OrderHasProduct generated by hbm2java
 */
@Entity
@Table(name="order_has_product"
    ,catalog="healthifyme"
)
public class OrderHasProduct  implements java.io.Serializable {


     private OrderHasProductId id;
     private Product product;
     private Order order;
     private int quantity;

    public OrderHasProduct() {
    }

    public OrderHasProduct(OrderHasProductId id, Product product, Order order, int quantity) {
       this.id = id;
       this.product = product;
       this.order = order;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="order_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ) } )
    public OrderHasProductId getId() {
        return this.id;
    }
    
    public void setId(OrderHasProductId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="order_id", referencedColumnName="id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="user_id", referencedColumnName="user_id", nullable=false, insertable=false, updatable=false) } )
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


