// default package
// Generated Mar 5, 2023, 4:36:11 PM by Hibernate Tools 6.0.0.Alpha2
package gov.iti.jets.healthifyme.models;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * OrderHasProductId generated by hbm2java
 */
@Embeddable
public class OrderHasProductId  implements java.io.Serializable {


     private int orderId;
     private int userId;
     private int productId;

    public OrderHasProductId() {
    }

    public OrderHasProductId(int orderId, int userId, int productId) {
       this.orderId = orderId;
       this.userId = userId;
       this.productId = productId;
    }
   


    @Column(name="order_id", nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderHasProductId) ) return false;
		 OrderHasProductId castOther = ( OrderHasProductId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getUserId()==castOther.getUserId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


