// default package
// Generated Mar 5, 2023, 4:36:11 PM by Hibernate Tools 6.0.0.Alpha2
package gov.iti.jets.healthifyme.models;

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="healthifyme"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class Product  implements java.io.Serializable {


     private ProductId id;
     private User user;
     private Category category;
     private String name;
     private String description;
     private int quantity;
     private long price;
     private String image;
     private Set<OrderHasProduct> orderHasProducts = new HashSet<OrderHasProduct>(0);

    public Product() {
    }

	
    public Product(ProductId id, User user, Category category, String name, int quantity, long price) {
        this.id = id;
        this.user = user;
        this.category = category;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
    }
    public Product(ProductId id, User user, Category category, String name, String description, int quantity, long price, String image, Set<OrderHasProduct> orderHasProducts) {
       this.id = id;
       this.user = user;
       this.category = category;
       this.name = name;
       this.description = description;
       this.quantity = quantity;
       this.price = price;
       this.image = image;
       this.orderHasProducts = orderHasProducts;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", unique=true, nullable=false) ), 
        @AttributeOverride(name="categoryId", column=@Column(name="category_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public ProductId getId() {
        return this.id;
    }
    
    public void setId(ProductId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false, insertable=false, updatable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=10, scale=0)
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }

    
    @Column(name="image", length=200)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<OrderHasProduct> getOrderHasProducts() {
        return this.orderHasProducts;
    }
    
    public void setOrderHasProducts(Set<OrderHasProduct> orderHasProducts) {
        this.orderHasProducts = orderHasProducts;
    }




}


