// default package
// Generated Mar 5, 2023, 4:36:11 PM by Hibernate Tools 6.0.0.Alpha2

package gov.iti.jets.healthifyme.models;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * ProductId generated by hbm2java
 */
@Embeddable
public class ProductId  implements java.io.Serializable {


     private int id;
     private int categoryId;
     private int userId;

    public ProductId() {
    }

    public ProductId(int id, int categoryId, int userId) {
       this.id = id;
       this.categoryId = categoryId;
       this.userId = userId;
    }
   


    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="category_id", nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductId) ) return false;
		 ProductId castOther = ( ProductId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCategoryId()==castOther.getCategoryId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCategoryId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


