// default package
// Generated Mar 5, 2023, 4:36:11 PM by Hibernate Tools 6.0.0.Alpha2
package gov.iti.jets.healthifyme.models;

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,catalog="healthifyme"
)
public class Roles  implements java.io.Serializable {


     private int id;
     private String role;
     private Set<User> users = new HashSet<User>(0);

    public Roles() {
    }

	
    public Roles(int id, String role) {
        this.id = id;
        this.role = role;
    }
    public Roles(int id, String role, Set<User> users) {
       this.id = id;
       this.role = role;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="role", nullable=false, length=45)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_roles", catalog="healthifyme", joinColumns = { 
        @JoinColumn(name="roles_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


