// default package
// Generated Mar 5, 2023, 4:36:11 PM by Hibernate Tools 6.0.0.Alpha2

package gov.iti.jets.healthifyme.models;

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="healthifyme"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String phone;
     private String email;
     private String password;
     private String role;
     private Long walletBalance;
     private String address;
     private Set<Roles> roleses = new HashSet<Roles>(0);
     private Set<Product> products = new HashSet<Product>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public User() {
    }

	
    public User(String phone, String email, String password, String role) {
        this.phone = phone;
        this.email = email;
        this.password = password;
        this.role = role;
    }
    public User(String phone, String email, String password, String role, Long walletBalance, String address, Set<Roles> roleses, Set<Product> products, Set<Order> orders) {
       this.phone = phone;
       this.email = email;
       this.password = password;
       this.role = role;
       this.walletBalance = walletBalance;
       this.address = address;
       this.roleses = roleses;
       this.products = products;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="phone", nullable=false, length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="role", nullable=false, length=45)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="wallet_balance", precision=10, scale=0)
    public Long getWalletBalance() {
        return this.walletBalance;
    }
    
    public void setWalletBalance(Long walletBalance) {
        this.walletBalance = walletBalance;
    }

    
    @Column(name="address", length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_roles", catalog="healthifyme", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="roles_id", nullable=false, updatable=false) })
    public Set<Roles> getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set<Roles> roleses) {
        this.roleses = roleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


